name: Autogen PR
on:
  workflow_dispatch:
    inputs:
      path:
        description: "Target file path (relative to repo)"
        required: true
        default: "README.md"
      instruction:
        description: "What to generate/update"
        required: true
        default: "Add a quick start section."

jobs:
  autogen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -U pip openai==1.* pytest || true

      - name: Generate/Update file via OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python tools/autogen.py \
            --path "${{ inputs.path }}" \
            --instruction "${{ inputs.instruction }}"

      - name: Run tests (optional)
        continue-on-error: true
        run: pytest -q || echo "pytest failed"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "autogen: update ${{ inputs.path }}"
          title: "autogen: update ${{ inputs.path }}"
          body: |
            Instruction:
            ```
            ${{ inputs.instruction }}
            ```
            Auto-generated by Autogen PR workflow.
          branch: "autogen/${{ github.run_id }}"
          labels: |
            autogen
