name: CI
on:
  push:
    branches: [main, beta, exp]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.cfg'
  pull_request:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.cfg'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - run: pip install -U pip pytest || true
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install fastapi httpx; fi
      - run: pip install -e . || true
      - run: pytest -q

  notify:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ CI failed on ${{ github.repository }} @ ${{ github.ref_name }}"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          html_body: |
            <p>CI failed for <b>${{ github.repository }}</b> @ <b>${{ github.ref_name }}</b></p>
            <p>Run: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">view logs</a></p>

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ CI passed on ${{ github.repository }} @ ${{ github.ref_name }}"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          secure: true
          html_body: |
            <p>CI passed for <b>${{ github.repository }}</b> @ <b>${{ github.ref_name }}</b></p>
            <p>Run: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">view logs</a></p>
