name: CI
on:
  push:
    branches: [main, beta, exp]
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.cfg'
  pull_request:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'setup.cfg'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11","3.12","3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - run: pip install -U pip pytest || true
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install fastapi httpx; fi
      - run: pip install -e . || true
      - run: pytest -q
