name: Deploy to Cloud Run (matrix)

on:
  push:
    branches: [ "main", "beta", "exp" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  REGION: asia-northeast3
  PROJECT_ID: ust-multiverse-dev
  PROJECT_NUMBER: 128056465529
  IMAGE_REPO: cloud-run-source-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.out.outputs.image }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CI_SA }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'beta'

      - name: Build & Push (buildpacks) — wait until SUCCESS
        id: out
        run: |
          set -euo pipefail
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPO }}/app:${GITHUB_SHA}"

          # Submit async (로그 스트리밍 권한 문제 회피)
          gcloud builds submit \
            --pack image="$IMAGE" \
            --gcs-source-staging-dir "gs://${{ env.PROJECT_NUMBER }}-cloudbuild/source" \
            --async

          # 가장 최근 해당 이미지 빌드 ID 찾기
          BID=""
          for i in {1..30}; do
            BID=$(gcloud builds list \
              --filter="images:$IMAGE" \
              --sort-by="~createTime" \
              --format="value(ID)" \
              --limit=1 \
              --project ${{ env.PROJECT_ID }})
            if [[ -n "$BID" ]]; then break; fi
            echo "Waiting for build to appear... ($i)"
            sleep 5
          done
          if [[ -z "$BID" ]]; then
            echo "ERROR: Build ID not found for image $IMAGE"
            exit 1
          fi
          echo "Build ID: $BID"

          # 완료까지 상태 폴링
          STATUS=""
          for i in {1..120}; do
            STATUS=$(gcloud builds describe "$BID" --project ${{ env.PROJECT_ID }} --format="value(status)")
            echo "Build status: $STATUS (t=$((i*5))s)"
            case "$STATUS" in
              SUCCESS) break ;;
              FAILURE|CANCELLED|EXPIRED) echo "Build ended with $STATUS"; exit 1 ;;
              *) sleep 5 ;;
            esac
          done
          if [[ "$STATUS" != "SUCCESS" ]]; then
            echo "ERROR: Build did not reach SUCCESS"
            exit 1
          fi

          # 출력으로 이미지 태그 전달
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [cloudrun-main, cloudrun-beta, cloudrun-exp]
    permissions:
      contents: read
      id-token: write
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CI_SA }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'beta'

      - name: Deploy ${{ matrix.svc }}
        run: |
          set -e
          IMAGE="${{ needs.build.outputs.image }}"
          gcloud run deploy "${{ matrix.svc }}" \
            --image "$IMAGE" \
            --region "${{ env.REGION }}" \
            --allow-unauthenticated \
            --project "${{ env.PROJECT_ID }}"

      - name: Smoke /health ${{ matrix.svc }}
        run: |
          set -e
          URL=$(gcloud run services describe "${{ matrix.svc }}" --region "${{ env.REGION }}" --project "${{ env.PROJECT_ID }}" --format='value(status.url)')
          echo "Check: $URL/health"
          curl -fsSL "$URL/health" >/dev/null
          echo "OK"

      - name: Slack notify
        if: ${{ always() && env.SLACK_WEBHOOK_URL != '' }}
        run: |
          STATUS="${{ job.status }}"
          SVC="${{ matrix.svc }}"
          URL=$(gcloud run services describe "$SVC" --region "${{ env.REGION }}" --project "${{ env.PROJECT_ID }}" --format='value(status.url)')
          MSG="[$STATUS] $SVC -> $URL  (@ ${GITHUB_SHA:0:7})"
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$MSG\"}" "${SLACK_WEBHOOK_URL}"
