name: notify-on-status

on:
  workflow_run:
    workflows: ["Deploy to Cloud Run (matrix)", "Auto Multiverse Codegen → exp"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from:     ${{ secrets.SMTP_FROM }}
          to:       ${{ secrets.SMTP_TO }}  # ← 반드시 있어야 함
          subject:  "[CI] ${{ github.event.workflow.name }} - ${{ github.event.workflow_run.conclusion }}"
          body: |
            Repo:   ${{ github.repository }}
            Actor:  ${{ github.actor }}
            Run:    https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
            Status: ${{ github.event.workflow_run.conclusion }}
