name: notify-on-status
on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]
jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' || github.event.workflow_run.previous_conclusion == 'failure' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build subject/body
        id: msg
        run: |
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          NAME="${{ github.event.workflow_run.name }}"
          BRANCH="${{ github.event.workflow_run.head_branch }}"
          URL="${{ github.event.workflow_run.html_url }}"
          if [ "$CONCLUSION" = "success" ]; then
            SUBJECT="✅ FIXED: $NAME on $BRANCH"
            BODY="The workflow is back to green.\n$URL"
          else
            SUBJECT="❌ FAILED: $NAME on $BRANCH"
            BODY="Please check the logs.\n$URL"
          fi
          {
            echo "subject<<EOF"; echo "$SUBJECT"; echo "EOF";
            echo "body<<EOF";    echo -e "$BODY"; echo "EOF";
          } >> "$GITHUB_OUTPUT"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: ${{ steps.msg.outputs.subject }}
          to: ${{ secrets.ALERT_TO_EMAIL }}
          from: "CI Bot <${{ secrets.SMTP_USERNAME }}>"
          content_type: text/plain
          body: ${{ steps.msg.outputs.body }}
